# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'redimencionarImg.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(380, 600)
        MainWindow.setMinimumSize(QtCore.QSize(380, 600))
        MainWindow.setMaximumSize(QtCore.QSize(380, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 360, 401))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_Image = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_Image.setText("")
        self.label_Image.setObjectName("label_Image")
        self.verticalLayout_2.addWidget(self.label_Image)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.input_Url_Img = QtWidgets.QLineEdit(self.centralwidget)
        self.input_Url_Img.setObjectName("input_Url_Img")
        self.verticalLayout.addWidget(self.input_Url_Img)
        self.btn_BuscarImg = QtWidgets.QPushButton(self.centralwidget)
        self.btn_BuscarImg.setObjectName("btn_BuscarImg")
        self.verticalLayout.addWidget(self.btn_BuscarImg)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(0, 80))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.input_Largura = QtWidgets.QLineEdit(self.frame)
        self.input_Largura.setObjectName("input_Largura")
        self.gridLayout.addWidget(self.input_Largura, 0, 0, 1, 1)
        self.input_Altura = QtWidgets.QLineEdit(self.frame)
        self.input_Altura.setObjectName("input_Altura")
        self.gridLayout.addWidget(self.input_Altura, 0, 1, 1, 1)
        self.btn_Redimencionar = QtWidgets.QPushButton(self.frame)
        self.btn_Redimencionar.setObjectName("btn_Redimencionar")
        self.gridLayout.addWidget(self.btn_Redimencionar, 1, 0, 1, 2)
        self.verticalLayout.addWidget(self.frame)
        self.salvar = QtWidgets.QPushButton(self.centralwidget)
        self.salvar.setObjectName("salvar")
        self.verticalLayout.addWidget(self.salvar)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Redimencionar Imagem"))
        self.input_Url_Img.setPlaceholderText(_translate("MainWindow", "url imagem"))
        self.btn_BuscarImg.setText(_translate("MainWindow", "Buscar Imagem"))
        self.input_Largura.setPlaceholderText(_translate("MainWindow", "Largura"))
        self.input_Altura.setPlaceholderText(_translate("MainWindow", "Altura"))
        self.btn_Redimencionar.setText(_translate("MainWindow", "Redimencionar Imagem"))
        self.salvar.setText(_translate("MainWindow", "Salvar  Imagem"))
